### ISSUE TITLE
Hack the Vote game

### ISSUE THREAD

**Issue by zerosum0x0** [dsasmblr/hacking-online-games#1]
I saw you had some Pwn Adventure 3 writeups which is good stuff. 

Hack the Vote CTF 2016 had a video game hacking challenge based on Minetest. It included defeating a rather basic anti-cheat. There were only a few solves, and I didn't see any other writeups at the time. It's also game cheating from Linux which is a little bit unique.

https://zerosum0x0.blogspot.com/2016/11/hack-vote-wall-solution.html

**Comment by dsasmblr** [comment]
That Trump wall, lol. Amazing. Thanks for sharing; I'll add it shortly!
